# Generated by Django 4.0.5 on 2022-06-11 14:11

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_is_deleted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='cuantity',
            new_name='quantity',
        ),
    ]
